image: docker:git

variables:
  GIT_LFS_SKIP_SMUDGE: 1 # Avoid fetching the files from LFS when doing git fetch
  TMPDIR: "${CI_PROJECT_DIR}.tmp"
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

services:
  - docker:dind

stages:
  - build


before_script:
  - 'echo "New job started"'
  - 'echo "Project name: $CI_PROJECT_NAME."'
  - 'echo "Commit ref: $CI_COMMIT_REF_NAME."'
# inspired from https://molecule.readthedocs.io/en/latest/ci.html
  - apk add --no-cache python3 python3-dev

gen_docker:
  stage: build
  script:
    - 'echo "${MOUNT_POINT}"'
    - mkdir -p "$MOUNT_POINT"
    - chmod a+rw $MOUNT_POINT
    - 'echo "name: $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"'
    - docker build . -t ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}
    - wget -O test_docker_call.py https://raw.githubusercontent.com/eurobench/docker_test/master/test_docker_call.py
    - export DOCKER_IMAGE='${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}'
    - export TEST_PLAN='test_data/test_plan.xml'
    - export OUT_FOLDER="${MOUNT_POINT}"
    - python3 test_docker_call.py

# test_docker:
#   stage: test

#   script:
#     - wget -O test_docker_call.py https://raw.githubusercontent.com/eurobench/docker_test/master/test_docker_call.py
#     - export DOCKER_IMAGE='${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}'
#     - export TEST_PLAN='test_data/test_plan.xml'
#     - python3 test_docker_call.py

# deploy_docker:
#   stage: deploy
#   tags:
#     - ci
#   script:
#     #- docker save -o pi_csic_docker_image.tar pi_csic_docker_image
#     - docker login ${ARTIFACT_DOCKER_URL} -u ${ARTIFACT_CI_USER} -p ${ARTIFACT_CI_TOKEN}
#     - docker push ${ARTIFACT_DOCKER_URL}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}

after_script:
  - echo "Job finished, well done"
